version: '3.8'

services:
  frontend:
    build: ./
    working_dir: /app
    volumes:
      - ./frontend:/app:Z
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5001
    command: ["/bin/sh", "-c", "/app/scripts/development.sh"]

  backend:
    build: ./
    working_dir: /app/backend:Z
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:password@database:5432/mydb
    command: ["/bin/sh", "-c", "/app/scripts/development.sh"]

  database:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data: